### ISSUE TITLE
Error using data.table() with xls sources

### ISSUE THREAD

**Issue by famuvie** [KentonWhite/ProjectTemplate#137] opened 2015-08-04 15:25 UTC
Here is a [MRE](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example):

``` R
## Create a test project to reveal the issue
library(ProjectTemplate)
create.project('testxls')
setwd('testxls')

## Write a dummy xls data file
require(xlsx)
write.xlsx(data.frame(x=1), file = 'data/dummy.xls')

## Load project
load.project(override.config = list(data_tables = TRUE))
```

... which produces the following output:

```
Loading project configuration
Autoloading helper functions
 Running helper script: helpers.R
Autoloading cache
Autoloading data
 Loading data set: dummy
Loading required namespace: gdata
Loading required package: data.table
data.table 1.9.4  For help type: ?data.table
*** NB: by=.EACHI is now explicit. See README to restore previous behaviour.
Converting data.frames to data.tables
Error in get(data.set, envir = .TargetEnv) : object 'dummy' not found
```

**Comment by famuvie** [comment] 2015-08-04 15:27
The problem is in the `xls.reader()`.
As `xls` files may have multiple sheets, it creates `variable.name`s with a suffix `.Sheet.n`.
But then, `.convert.to.data.table()` looks for `variable.name` which is not found.

**Comment by famuvie** [comment] 2015-08-04 15:38
Furthermore, I think that the following sentence in `convert.to.data.table()`
```R
get(data.set, envir = .TargetEnv)
```
should specify `inherits = FALSE`, for extra-safety.
In my test before, I originally used the file name `test.xls`. 
At this point, the variable name was `test.Sheet1`, but the `get` mistakenly found `test` as the name of an available function.

**Comment by KentonWhite** [comment] 2015-08-05 15:19
Thanks for the suggestions! I like the idea of setting inherits = FALSE in the get statements. There are several other places where this might make sense, not just in convert.to.data.table. Would you be willing to make a PR with the change?

How to handle Excel workbooks is a bit of a struggle. Since Excel workbooks can have multiple sheets, it is fairly standard to append the sheet name to workbook name. This makes it difficult to load the Excel files in other modules. 

If I understand the problem, it is that Excel sheets are not being converted to data tables. Perhaps the only way to fix this is to handle the data table conversion in the Excel reader. Would that fix your problems?

**Comment by famuvie** [comment] 2015-08-06 12:51
No, that would not fix the problem.
It will get the sheets converted to data.table, but `.load.data()` will still return a vector of variable names which is incorrect (having an instance of `xlsfile` rather than `xlsfile.Sheet1`).

This vector will go into `my.project.info$data$ and will eventually cause the same problem in `.convert.to.data.table()`: the variable will not be found.

I propose a quick fix by accounting specifically for these readers within `.load.data()`.
I feel a bit like [here](https://pbs.twimg.com/tweet_video/CFYeMeRWIAAaBxv.mp4) but it works... :)

**Comment by KentonWhite** [comment] 2015-08-16 18:17
Thanks for the PR's. I've been laid up for the past week and just getting back to work. Sorry that this has been delayed on my end. Let me look at the proposed solutions in more detail this week and we can discuss. Again sorry for the delay.

**Comment by Hugovdberg** [comment] 2017-01-15 16:03
I think the remaining problem of multiple/changed variable names being created by a reader is fixed by #187 with the adapted `.load.data` function.

**Comment by KentonWhite** [comment] 2017-01-16 16:13
I'll see how #187 processes and see if it fixes this issue.

**Comment by KentonWhite** [comment] 2018-04-27 16:11
#187 should have solved this issue.  Closing.  Please re-open if the issue is still there.

**Closed by KentonWhite** 2018-04-27 16:11 UTC
Labels: Bug
