### ISSUE TITLE
`create.project` fails even on full path when inside an existing project

### ISSUE THREAD

**Issue by Hugovdberg** [KentonWhite/ProjectTemplate#210] opened 2017-10-03 14:10 UTC
I noticed an error with `create.project` when creating a project specified by a full path, when the working directory is set to a ProjectTemplate project directory. Even though a full path to the new template is specified the `.stopifproject` error is triggered.

How to reproduce:

- Create a project directory using `create.project`
- Set working directory to the new project
- Create a project directory at a new full path using `create.project` again (for example `create.project(tempdir())`)

Possible solution:

- wrap `.stopifproject` calls in a conditional `if (dirname(project.name)=='.'){}`

Is this something we want to implement or should we just expect users to always create a project (and subsequently templates in the current implementation) from outside an existing project? (KISS vs. convenience)

**Comment by KentonWhite** [comment] 2018-04-20 17:30
I think users should always create a project outside of an existing project.  What would be the use case for nested projects?

**Comment by Hugovdberg** [comment] 2018-04-22 08:11
Technically the custom templates are new projects, so if you happen to be in a project directory when you try to create a new template you get an error. The error is triggered even if the target directory is outside the current directory. A completely valid call to `create.template` will therefore fail if called from the wrong working directory.

**Comment by rsangole** [comment] 2018-04-22 11:12
> A completely valid call to create.template will therefore fail if called from the wrong working directory. A completely valid call to create.template will therefore fail if called from the wrong working directory.

I have faced this a few times. Today, have to go through the manual task of changing working dir first creating a new project someplace else, and then changing working dir back again.

**Comment by KentonWhite** [comment] 2018-04-22 12:44
So should this be fixed only form `create.template`?  Or fixing it for `create.template` also fixes it for `create.project`?

**Comment by Hugovdberg** [comment] 2018-04-23 09:44
I just realised we could probably alter `.stopifproject` to take a path as an argument, so that it can actually check the parent of the target directory instead of the current. That would fix both `create.project` and `create.template`.

**Comment by rsangole** [comment] 2018-04-24 17:44
When I was working on #234 , I found that `create.project()` has two calls to `.stopifproject` which seem redundant. 

https://github.com/KentonWhite/ProjectTemplate/blob/8072e518c3b286aca862104ad36f2ca6bc0cfc62/R/create.project.R#L49-L54

The 1st call works fine and stops correctly. If the 1st call is commented out, the 2nd call does not work correctly and creates a project within a project.

Just an FYI, we should probably look into this.

**Comment by KentonWhite** [comment] 2018-05-02 13:36
Closing this now since the issue is moved to #240

**Closed** 2018-05-02 16:40 UTC
Labels: Bug
